"""ImagineSignal controlled creative learning package."""

from adjacency.imagine_signal.canonical import canonical_json, content_sha256
from adjacency.imagine_signal.contracts import (
    AssetState,
    AuctionScenarioRecord,
    AuctionSensitivityRecord,
    BidderModel,
    BrandSpec,
    CampaignSpec,
    ConvergenceRecord,
    CostStatus,
    CreativeAsset,
    DataOrigin,
    DecisionReceipt,
    DeploymentMode,
    EvidenceClass,
    GenerationBudget,
    HumanApproval,
    LockedAttribute,
    MeasurementWindow,
    Mechanism,
    MutationSpec,
    NextAction,
    OutcomeSnapshot,
    SignalDecision,
    SignalEstimate,
    SignalGateResult,
    UncertaintyInterval,
)
from adjacency.imagine_signal.decisions import build_signal_decision
from adjacency.imagine_signal.mutations import (
    family_hash,
    plan_controlled_mutations,
    validate_controlled_family,
)
from adjacency.imagine_signal.receipts import build_decision_receipt, verify_receipt

__all__ = [
    "AssetState",
    "AuctionScenarioRecord",
    "AuctionSensitivityRecord",
    "BidderModel",
    "BrandSpec",
    "CampaignSpec",
    "ConvergenceRecord",
    "CostStatus",
    "CreativeAsset",
    "DataOrigin",
    "DecisionReceipt",
    "DeploymentMode",
    "EvidenceClass",
    "GenerationBudget",
    "HumanApproval",
    "LockedAttribute",
    "MeasurementWindow",
    "Mechanism",
    "MutationSpec",
    "NextAction",
    "OutcomeSnapshot",
    "SignalDecision",
    "SignalEstimate",
    "SignalGateResult",
    "UncertaintyInterval",
    "build_decision_receipt",
    "build_signal_decision",
    "canonical_json",
    "content_sha256",
    "family_hash",
    "plan_controlled_mutations",
    "validate_controlled_family",
    "verify_receipt",
]
